name: mcp_dart
description: Dart Implementation of Model Context Protocol (MCP) SDK.
version: 2.0.0
repository: https://github.com/leehack/mcp_dart
homepage: https://github.com/leehack/mcp_dart
issue_tracker: https://github.com/leehack/mcp_dart/issues
documentation: https://pub.dev/documentation/mcp_dart/latest/
topics:
  - mcp
  - ai
  - llm
  - server
  - client

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  path: ^1.9.1
  test: ^1.24.0
