name: mcp_dart_cli
description: CLI for Model Context Protocol (MCP) servers in Dart.
version: 0.1.1
repository: https://github.com/leehack/mcp_dart

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  mason: ^0.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

executables:
  mcp_dart:
